name: Security & Dependency Check

on:
  schedule:
    # Run every Monday at 9 AM
    - cron: '0 9 * * 1'
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run npm audit
        run: npm audit --audit-level moderate

      - name: Run npm audit fix
        run: npm audit fix --dry-run

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
